// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comms.proto

package comms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request_UploadBook struct {
	Chunks               []byte   `protobuf:"bytes,1,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Nombre               string   `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Cantidad             int32    `protobuf:"varint,3,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	Id                   int32    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_UploadBook) Reset()         { *m = Request_UploadBook{} }
func (m *Request_UploadBook) String() string { return proto.CompactTextString(m) }
func (*Request_UploadBook) ProtoMessage()    {}
func (*Request_UploadBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{0}
}

func (m *Request_UploadBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_UploadBook.Unmarshal(m, b)
}
func (m *Request_UploadBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_UploadBook.Marshal(b, m, deterministic)
}
func (m *Request_UploadBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_UploadBook.Merge(m, src)
}
func (m *Request_UploadBook) XXX_Size() int {
	return xxx_messageInfo_Request_UploadBook.Size(m)
}
func (m *Request_UploadBook) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_UploadBook.DiscardUnknown(m)
}

var xxx_messageInfo_Request_UploadBook proto.InternalMessageInfo

func (m *Request_UploadBook) GetChunks() []byte {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func (m *Request_UploadBook) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *Request_UploadBook) GetCantidad() int32 {
	if m != nil {
		return m.Cantidad
	}
	return 0
}

func (m *Request_UploadBook) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response_UploadBook struct {
	State                int32    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_UploadBook) Reset()         { *m = Response_UploadBook{} }
func (m *Response_UploadBook) String() string { return proto.CompactTextString(m) }
func (*Response_UploadBook) ProtoMessage()    {}
func (*Response_UploadBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{1}
}

func (m *Response_UploadBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_UploadBook.Unmarshal(m, b)
}
func (m *Response_UploadBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_UploadBook.Marshal(b, m, deterministic)
}
func (m *Response_UploadBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_UploadBook.Merge(m, src)
}
func (m *Response_UploadBook) XXX_Size() int {
	return xxx_messageInfo_Response_UploadBook.Size(m)
}
func (m *Response_UploadBook) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_UploadBook.DiscardUnknown(m)
}

var xxx_messageInfo_Response_UploadBook proto.InternalMessageInfo

func (m *Response_UploadBook) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type Request_Distribuir struct {
	Chunks               []byte   `protobuf:"bytes,1,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Nombre               string   `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Id                   int32    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Distribuir) Reset()         { *m = Request_Distribuir{} }
func (m *Request_Distribuir) String() string { return proto.CompactTextString(m) }
func (*Request_Distribuir) ProtoMessage()    {}
func (*Request_Distribuir) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{2}
}

func (m *Request_Distribuir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Distribuir.Unmarshal(m, b)
}
func (m *Request_Distribuir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Distribuir.Marshal(b, m, deterministic)
}
func (m *Request_Distribuir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Distribuir.Merge(m, src)
}
func (m *Request_Distribuir) XXX_Size() int {
	return xxx_messageInfo_Request_Distribuir.Size(m)
}
func (m *Request_Distribuir) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Distribuir.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Distribuir proto.InternalMessageInfo

func (m *Request_Distribuir) GetChunks() []byte {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func (m *Request_Distribuir) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *Request_Distribuir) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response_Distribuir struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Distribuir) Reset()         { *m = Response_Distribuir{} }
func (m *Response_Distribuir) String() string { return proto.CompactTextString(m) }
func (*Response_Distribuir) ProtoMessage()    {}
func (*Response_Distribuir) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{3}
}

func (m *Response_Distribuir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Distribuir.Unmarshal(m, b)
}
func (m *Response_Distribuir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Distribuir.Marshal(b, m, deterministic)
}
func (m *Response_Distribuir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Distribuir.Merge(m, src)
}
func (m *Response_Distribuir) XXX_Size() int {
	return xxx_messageInfo_Response_Distribuir.Size(m)
}
func (m *Response_Distribuir) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Distribuir.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Distribuir proto.InternalMessageInfo

type Request_Estado_M struct {
	Estado               int32    `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Estado_M) Reset()         { *m = Request_Estado_M{} }
func (m *Request_Estado_M) String() string { return proto.CompactTextString(m) }
func (*Request_Estado_M) ProtoMessage()    {}
func (*Request_Estado_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{4}
}

func (m *Request_Estado_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Estado_M.Unmarshal(m, b)
}
func (m *Request_Estado_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Estado_M.Marshal(b, m, deterministic)
}
func (m *Request_Estado_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Estado_M.Merge(m, src)
}
func (m *Request_Estado_M) XXX_Size() int {
	return xxx_messageInfo_Request_Estado_M.Size(m)
}
func (m *Request_Estado_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Estado_M.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Estado_M proto.InternalMessageInfo

func (m *Request_Estado_M) GetEstado() int32 {
	if m != nil {
		return m.Estado
	}
	return 0
}

type Response_Estado_M struct {
	Estado               int32    `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Estado_M) Reset()         { *m = Response_Estado_M{} }
func (m *Response_Estado_M) String() string { return proto.CompactTextString(m) }
func (*Response_Estado_M) ProtoMessage()    {}
func (*Response_Estado_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{5}
}

func (m *Response_Estado_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Estado_M.Unmarshal(m, b)
}
func (m *Response_Estado_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Estado_M.Marshal(b, m, deterministic)
}
func (m *Response_Estado_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Estado_M.Merge(m, src)
}
func (m *Response_Estado_M) XXX_Size() int {
	return xxx_messageInfo_Response_Estado_M.Size(m)
}
func (m *Response_Estado_M) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Estado_M.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Estado_M proto.InternalMessageInfo

func (m *Response_Estado_M) GetEstado() int32 {
	if m != nil {
		return m.Estado
	}
	return 0
}

type Request_Chunk struct {
	Nombre               string   `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Chunk) Reset()         { *m = Request_Chunk{} }
func (m *Request_Chunk) String() string { return proto.CompactTextString(m) }
func (*Request_Chunk) ProtoMessage()    {}
func (*Request_Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{6}
}

func (m *Request_Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Chunk.Unmarshal(m, b)
}
func (m *Request_Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Chunk.Marshal(b, m, deterministic)
}
func (m *Request_Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Chunk.Merge(m, src)
}
func (m *Request_Chunk) XXX_Size() int {
	return xxx_messageInfo_Request_Chunk.Size(m)
}
func (m *Request_Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Chunk proto.InternalMessageInfo

func (m *Request_Chunk) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

type Response_Chunk struct {
	Chunks               []byte   `protobuf:"bytes,1,opt,name=chunks,proto3" json:"chunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Chunk) Reset()         { *m = Response_Chunk{} }
func (m *Response_Chunk) String() string { return proto.CompactTextString(m) }
func (*Response_Chunk) ProtoMessage()    {}
func (*Response_Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{7}
}

func (m *Response_Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Chunk.Unmarshal(m, b)
}
func (m *Response_Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Chunk.Marshal(b, m, deterministic)
}
func (m *Response_Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Chunk.Merge(m, src)
}
func (m *Response_Chunk) XXX_Size() int {
	return xxx_messageInfo_Response_Chunk.Size(m)
}
func (m *Response_Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Chunk proto.InternalMessageInfo

func (m *Response_Chunk) GetChunks() []byte {
	if m != nil {
		return m.Chunks
	}
	return nil
}

type Request_WriteD struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_WriteD) Reset()         { *m = Request_WriteD{} }
func (m *Request_WriteD) String() string { return proto.CompactTextString(m) }
func (*Request_WriteD) ProtoMessage()    {}
func (*Request_WriteD) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{8}
}

func (m *Request_WriteD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_WriteD.Unmarshal(m, b)
}
func (m *Request_WriteD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_WriteD.Marshal(b, m, deterministic)
}
func (m *Request_WriteD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_WriteD.Merge(m, src)
}
func (m *Request_WriteD) XXX_Size() int {
	return xxx_messageInfo_Request_WriteD.Size(m)
}
func (m *Request_WriteD) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_WriteD.DiscardUnknown(m)
}

var xxx_messageInfo_Request_WriteD proto.InternalMessageInfo

type Response_WriteD struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_WriteD) Reset()         { *m = Response_WriteD{} }
func (m *Response_WriteD) String() string { return proto.CompactTextString(m) }
func (*Response_WriteD) ProtoMessage()    {}
func (*Response_WriteD) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{9}
}

func (m *Response_WriteD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_WriteD.Unmarshal(m, b)
}
func (m *Response_WriteD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_WriteD.Marshal(b, m, deterministic)
}
func (m *Response_WriteD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_WriteD.Merge(m, src)
}
func (m *Response_WriteD) XXX_Size() int {
	return xxx_messageInfo_Response_WriteD.Size(m)
}
func (m *Response_WriteD) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_WriteD.DiscardUnknown(m)
}

var xxx_messageInfo_Response_WriteD proto.InternalMessageInfo

type Request_PropuestaD struct {
	Propuesta            string   `protobuf:"bytes,1,opt,name=propuesta,proto3" json:"propuesta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_PropuestaD) Reset()         { *m = Request_PropuestaD{} }
func (m *Request_PropuestaD) String() string { return proto.CompactTextString(m) }
func (*Request_PropuestaD) ProtoMessage()    {}
func (*Request_PropuestaD) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{10}
}

func (m *Request_PropuestaD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_PropuestaD.Unmarshal(m, b)
}
func (m *Request_PropuestaD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_PropuestaD.Marshal(b, m, deterministic)
}
func (m *Request_PropuestaD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_PropuestaD.Merge(m, src)
}
func (m *Request_PropuestaD) XXX_Size() int {
	return xxx_messageInfo_Request_PropuestaD.Size(m)
}
func (m *Request_PropuestaD) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_PropuestaD.DiscardUnknown(m)
}

var xxx_messageInfo_Request_PropuestaD proto.InternalMessageInfo

func (m *Request_PropuestaD) GetPropuesta() string {
	if m != nil {
		return m.Propuesta
	}
	return ""
}

type Response_PropuestaD struct {
	Estado               int32    `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_PropuestaD) Reset()         { *m = Response_PropuestaD{} }
func (m *Response_PropuestaD) String() string { return proto.CompactTextString(m) }
func (*Response_PropuestaD) ProtoMessage()    {}
func (*Response_PropuestaD) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{11}
}

func (m *Response_PropuestaD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_PropuestaD.Unmarshal(m, b)
}
func (m *Response_PropuestaD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_PropuestaD.Marshal(b, m, deterministic)
}
func (m *Response_PropuestaD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_PropuestaD.Merge(m, src)
}
func (m *Response_PropuestaD) XXX_Size() int {
	return xxx_messageInfo_Response_PropuestaD.Size(m)
}
func (m *Response_PropuestaD) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_PropuestaD.DiscardUnknown(m)
}

var xxx_messageInfo_Response_PropuestaD proto.InternalMessageInfo

func (m *Response_PropuestaD) GetEstado() int32 {
	if m != nil {
		return m.Estado
	}
	return 0
}

type Request_RecursoD struct {
	Tiempo               string   `protobuf:"bytes,1,opt,name=tiempo,proto3" json:"tiempo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_RecursoD) Reset()         { *m = Request_RecursoD{} }
func (m *Request_RecursoD) String() string { return proto.CompactTextString(m) }
func (*Request_RecursoD) ProtoMessage()    {}
func (*Request_RecursoD) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{12}
}

func (m *Request_RecursoD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_RecursoD.Unmarshal(m, b)
}
func (m *Request_RecursoD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_RecursoD.Marshal(b, m, deterministic)
}
func (m *Request_RecursoD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_RecursoD.Merge(m, src)
}
func (m *Request_RecursoD) XXX_Size() int {
	return xxx_messageInfo_Request_RecursoD.Size(m)
}
func (m *Request_RecursoD) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_RecursoD.DiscardUnknown(m)
}

var xxx_messageInfo_Request_RecursoD proto.InternalMessageInfo

func (m *Request_RecursoD) GetTiempo() string {
	if m != nil {
		return m.Tiempo
	}
	return ""
}

type Response_RecursoD struct {
	Estado               int32    `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_RecursoD) Reset()         { *m = Response_RecursoD{} }
func (m *Response_RecursoD) String() string { return proto.CompactTextString(m) }
func (*Response_RecursoD) ProtoMessage()    {}
func (*Response_RecursoD) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{13}
}

func (m *Response_RecursoD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_RecursoD.Unmarshal(m, b)
}
func (m *Response_RecursoD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_RecursoD.Marshal(b, m, deterministic)
}
func (m *Response_RecursoD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_RecursoD.Merge(m, src)
}
func (m *Response_RecursoD) XXX_Size() int {
	return xxx_messageInfo_Response_RecursoD.Size(m)
}
func (m *Response_RecursoD) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_RecursoD.DiscardUnknown(m)
}

var xxx_messageInfo_Response_RecursoD proto.InternalMessageInfo

func (m *Response_RecursoD) GetEstado() int32 {
	if m != nil {
		return m.Estado
	}
	return 0
}

func init() {
	proto.RegisterType((*Request_UploadBook)(nil), "comms.Request_UploadBook")
	proto.RegisterType((*Response_UploadBook)(nil), "comms.Response_UploadBook")
	proto.RegisterType((*Request_Distribuir)(nil), "comms.Request_Distribuir")
	proto.RegisterType((*Response_Distribuir)(nil), "comms.Response_Distribuir")
	proto.RegisterType((*Request_Estado_M)(nil), "comms.Request_Estado_M")
	proto.RegisterType((*Response_Estado_M)(nil), "comms.Response_Estado_M")
	proto.RegisterType((*Request_Chunk)(nil), "comms.Request_Chunk")
	proto.RegisterType((*Response_Chunk)(nil), "comms.Response_Chunk")
	proto.RegisterType((*Request_WriteD)(nil), "comms.Request_Write_d")
	proto.RegisterType((*Response_WriteD)(nil), "comms.Response_Write_d")
	proto.RegisterType((*Request_PropuestaD)(nil), "comms.Request_Propuesta_d")
	proto.RegisterType((*Response_PropuestaD)(nil), "comms.Response_Propuesta_d")
	proto.RegisterType((*Request_RecursoD)(nil), "comms.Request_Recurso_d")
	proto.RegisterType((*Response_RecursoD)(nil), "comms.Response_Recurso_d")
}

func init() {
	proto.RegisterFile("comms.proto", fileDescriptor_db39efb7717b7d47)
}

var fileDescriptor_db39efb7717b7d47 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xbb, 0x8d, 0x4c, 0xf4, 0x6d, 0x2b, 0xd4, 0x74, 0x90, 0x05, 0x0e, 0xc8, 0x17, 0x26,
	0x40, 0x3d, 0xb0, 0x3f, 0x00, 0x89, 0xb5, 0x70, 0x61, 0xd2, 0x14, 0x40, 0x1c, 0x23, 0x37, 0xb6,
	0x84, 0xb5, 0x25, 0xce, 0x6c, 0xe7, 0xaf, 0xe7, 0x82, 0xed, 0x38, 0x4e, 0x70, 0x0b, 0x88, 0xdd,
	0xf2, 0x7e, 0xf8, 0xf3, 0x9e, 0xfd, 0xfd, 0x2a, 0x70, 0x54, 0x8a, 0xaa, 0x52, 0xcb, 0x46, 0x0a,
	0x2d, 0x50, 0xe2, 0x02, 0xdc, 0x00, 0xca, 0xd9, 0x5d, 0xcb, 0x94, 0x2e, 0xbe, 0x35, 0xb7, 0x82,
	0xd0, 0x0f, 0x42, 0xdc, 0xa0, 0xa7, 0x70, 0x58, 0xfe, 0x68, 0xeb, 0x1b, 0x95, 0xee, 0xbd, 0xdc,
	0x3b, 0x3f, 0xce, 0x7d, 0x64, 0xf3, 0xb5, 0xa8, 0x36, 0x92, 0xa5, 0xfb, 0x26, 0x3f, 0xcd, 0x7d,
	0x84, 0x32, 0x78, 0x58, 0x92, 0x5a, 0x73, 0x4a, 0x68, 0x7a, 0x60, 0x2a, 0x49, 0x1e, 0x62, 0x34,
	0x83, 0x7d, 0x4e, 0xd3, 0x07, 0x2e, 0x6b, 0xbe, 0xf0, 0x1b, 0x78, 0x92, 0x33, 0xd5, 0x88, 0x5a,
	0xb1, 0xf1, 0xc8, 0x05, 0x24, 0x4a, 0x13, 0xcd, 0xdc, 0xc4, 0x24, 0xef, 0x02, 0xfc, 0x75, 0x58,
	0x6f, 0xc5, 0x95, 0x96, 0x7c, 0xd3, 0x72, 0xf9, 0xdf, 0xeb, 0xc5, 0x2b, 0x9c, 0x8e, 0x56, 0x18,
	0xb0, 0xf8, 0x35, 0x3c, 0xee, 0x87, 0xad, 0xcd, 0x78, 0x2a, 0x8a, 0x2b, 0x8b, 0x64, 0xee, 0xdb,
	0xef, 0xe5, 0x23, 0x73, 0x8b, 0x79, 0x40, 0xfc, 0xb3, 0xf9, 0x15, 0x9c, 0xf4, 0xe0, 0x4b, 0xbb,
	0xe9, 0x9f, 0x16, 0xc5, 0xe7, 0x30, 0x0b, 0xd4, 0xd0, 0xb9, 0xeb, 0xaa, 0x78, 0x0e, 0x8f, 0x7a,
	0xe4, 0x77, 0xc9, 0x35, 0x2b, 0x28, 0x46, 0x76, 0x7d, 0x7f, 0xb8, 0xcf, 0x5d, 0xd8, 0x9b, 0x76,
	0x6d, 0xd7, 0x52, 0x34, 0xf6, 0x83, 0x14, 0x14, 0xbd, 0x80, 0x69, 0xd3, 0x87, 0x0e, 0x3c, 0xcd,
	0x87, 0x04, 0x5e, 0xc2, 0x22, 0x80, 0xc6, 0xa7, 0xfe, 0xfa, 0x16, 0xdd, 0x90, 0x9c, 0x95, 0xad,
	0x54, 0xa2, 0x6b, 0xd6, 0x9c, 0x55, 0x8d, 0xf0, 0x7c, 0x1f, 0xe1, 0xb7, 0x56, 0x51, 0x0f, 0xff,
	0xad, 0x7b, 0x17, 0xfa, 0xdd, 0xcf, 0x03, 0x48, 0x2e, 0xad, 0x51, 0xd1, 0x1a, 0x60, 0xe4, 0x96,
	0xb3, 0x65, 0xe7, 0xe5, 0x6d, 0xef, 0x66, 0x59, 0x28, 0x6d, 0x99, 0x0c, 0x4f, 0xd0, 0x67, 0x98,
	0x0f, 0x8a, 0x17, 0xde, 0x37, 0x31, 0x6d, 0xe8, 0xd8, 0xa6, 0x8d, 0xfc, 0x32, 0x41, 0x2b, 0x38,
	0xe9, 0xc4, 0xbf, 0x22, 0x77, 0x2d, 0xaf, 0x09, 0x7a, 0x16, 0x91, 0x7a, 0x6b, 0x64, 0x69, 0xcc,
	0xe9, 0x2b, 0x86, 0xf2, 0x1e, 0x66, 0x5f, 0xc4, 0x2d, 0x2f, 0xb9, 0x26, 0xb2, 0x53, 0x7d, 0x11,
	0x61, 0x5c, 0x36, 0x3b, 0x8d, 0x19, 0x2e, 0x6d, 0x00, 0x9f, 0x00, 0x82, 0x4e, 0x2b, 0x94, 0x45,
	0x87, 0x47, 0x12, 0x66, 0xcf, 0x63, 0xc4, 0xa8, 0x68, 0x40, 0x1f, 0xe1, 0x68, 0x78, 0xad, 0xd5,
	0xfd, 0x5f, 0x79, 0x0d, 0xc7, 0xd7, 0x8c, 0x72, 0xe9, 0x05, 0x46, 0x69, 0x04, 0x0a, 0xc2, 0x67,
	0x67, 0x31, 0x27, 0x94, 0xf0, 0x64, 0x73, 0xe8, 0x7e, 0x55, 0x17, 0xbf, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xac, 0xba, 0x3d, 0x58, 0xb9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommsClient is the client API for Comms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommsClient interface {
	UploadBook(ctx context.Context, in *Request_UploadBook, opts ...grpc.CallOption) (*Response_UploadBook, error)
	DistribuirChunks(ctx context.Context, in *Request_Distribuir, opts ...grpc.CallOption) (*Response_Distribuir, error)
	EstadoMaquina(ctx context.Context, in *Request_Estado_M, opts ...grpc.CallOption) (*Response_Estado_M, error)
	SolicitarChunk(ctx context.Context, in *Request_Chunk, opts ...grpc.CallOption) (*Response_Chunk, error)
	PropuestaD(ctx context.Context, in *Request_PropuestaD, opts ...grpc.CallOption) (*Response_PropuestaD, error)
	UploadBookD(ctx context.Context, in *Request_UploadBook, opts ...grpc.CallOption) (*Response_UploadBook, error)
	PedirRecurso(ctx context.Context, in *Request_RecursoD, opts ...grpc.CallOption) (*Response_RecursoD, error)
}

type commsClient struct {
	cc grpc.ClientConnInterface
}

func NewCommsClient(cc grpc.ClientConnInterface) CommsClient {
	return &commsClient{cc}
}

func (c *commsClient) UploadBook(ctx context.Context, in *Request_UploadBook, opts ...grpc.CallOption) (*Response_UploadBook, error) {
	out := new(Response_UploadBook)
	err := c.cc.Invoke(ctx, "/comms.Comms/UploadBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) DistribuirChunks(ctx context.Context, in *Request_Distribuir, opts ...grpc.CallOption) (*Response_Distribuir, error) {
	out := new(Response_Distribuir)
	err := c.cc.Invoke(ctx, "/comms.Comms/Distribuir_chunks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) EstadoMaquina(ctx context.Context, in *Request_Estado_M, opts ...grpc.CallOption) (*Response_Estado_M, error) {
	out := new(Response_Estado_M)
	err := c.cc.Invoke(ctx, "/comms.Comms/EstadoMaquina", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) SolicitarChunk(ctx context.Context, in *Request_Chunk, opts ...grpc.CallOption) (*Response_Chunk, error) {
	out := new(Response_Chunk)
	err := c.cc.Invoke(ctx, "/comms.Comms/SolicitarChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) PropuestaD(ctx context.Context, in *Request_PropuestaD, opts ...grpc.CallOption) (*Response_PropuestaD, error) {
	out := new(Response_PropuestaD)
	err := c.cc.Invoke(ctx, "/comms.Comms/PropuestaD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) UploadBookD(ctx context.Context, in *Request_UploadBook, opts ...grpc.CallOption) (*Response_UploadBook, error) {
	out := new(Response_UploadBook)
	err := c.cc.Invoke(ctx, "/comms.Comms/UploadBookD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) PedirRecurso(ctx context.Context, in *Request_RecursoD, opts ...grpc.CallOption) (*Response_RecursoD, error) {
	out := new(Response_RecursoD)
	err := c.cc.Invoke(ctx, "/comms.Comms/PedirRecurso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommsServer is the server API for Comms service.
type CommsServer interface {
	UploadBook(context.Context, *Request_UploadBook) (*Response_UploadBook, error)
	DistribuirChunks(context.Context, *Request_Distribuir) (*Response_Distribuir, error)
	EstadoMaquina(context.Context, *Request_Estado_M) (*Response_Estado_M, error)
	SolicitarChunk(context.Context, *Request_Chunk) (*Response_Chunk, error)
	PropuestaD(context.Context, *Request_PropuestaD) (*Response_PropuestaD, error)
	UploadBookD(context.Context, *Request_UploadBook) (*Response_UploadBook, error)
	PedirRecurso(context.Context, *Request_RecursoD) (*Response_RecursoD, error)
}

// UnimplementedCommsServer can be embedded to have forward compatible implementations.
type UnimplementedCommsServer struct {
}

func (*UnimplementedCommsServer) UploadBook(ctx context.Context, req *Request_UploadBook) (*Response_UploadBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBook not implemented")
}
func (*UnimplementedCommsServer) DistribuirChunks(ctx context.Context, req *Request_Distribuir) (*Response_Distribuir, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistribuirChunks not implemented")
}
func (*UnimplementedCommsServer) EstadoMaquina(ctx context.Context, req *Request_Estado_M) (*Response_Estado_M, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstadoMaquina not implemented")
}
func (*UnimplementedCommsServer) SolicitarChunk(ctx context.Context, req *Request_Chunk) (*Response_Chunk, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarChunk not implemented")
}
func (*UnimplementedCommsServer) PropuestaD(ctx context.Context, req *Request_PropuestaD) (*Response_PropuestaD, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PropuestaD not implemented")
}
func (*UnimplementedCommsServer) UploadBookD(ctx context.Context, req *Request_UploadBook) (*Response_UploadBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBookD not implemented")
}
func (*UnimplementedCommsServer) PedirRecurso(ctx context.Context, req *Request_RecursoD) (*Response_RecursoD, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PedirRecurso not implemented")
}

func RegisterCommsServer(s *grpc.Server, srv CommsServer) {
	s.RegisterService(&_Comms_serviceDesc, srv)
}

func _Comms_UploadBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_UploadBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).UploadBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/UploadBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).UploadBook(ctx, req.(*Request_UploadBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_DistribuirChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_Distribuir)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).DistribuirChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/DistribuirChunks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).DistribuirChunks(ctx, req.(*Request_Distribuir))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_EstadoMaquina_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_Estado_M)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).EstadoMaquina(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/EstadoMaquina",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).EstadoMaquina(ctx, req.(*Request_Estado_M))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_SolicitarChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_Chunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).SolicitarChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/SolicitarChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).SolicitarChunk(ctx, req.(*Request_Chunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_PropuestaD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_PropuestaD)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).PropuestaD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/PropuestaD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).PropuestaD(ctx, req.(*Request_PropuestaD))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_UploadBookD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_UploadBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).UploadBookD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/UploadBookD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).UploadBookD(ctx, req.(*Request_UploadBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_PedirRecurso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_RecursoD)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).PedirRecurso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/PedirRecurso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).PedirRecurso(ctx, req.(*Request_RecursoD))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comms.Comms",
	HandlerType: (*CommsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadBook",
			Handler:    _Comms_UploadBook_Handler,
		},
		{
			MethodName: "Distribuir_chunks",
			Handler:    _Comms_DistribuirChunks_Handler,
		},
		{
			MethodName: "EstadoMaquina",
			Handler:    _Comms_EstadoMaquina_Handler,
		},
		{
			MethodName: "SolicitarChunk",
			Handler:    _Comms_SolicitarChunk_Handler,
		},
		{
			MethodName: "PropuestaD",
			Handler:    _Comms_PropuestaD_Handler,
		},
		{
			MethodName: "UploadBookD",
			Handler:    _Comms_UploadBookD_Handler,
		},
		{
			MethodName: "PedirRecurso",
			Handler:    _Comms_PedirRecurso_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comms.proto",
}
