// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comms.proto

package comms

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request_UploadBook struct {
	Chunks               []byte   `protobuf:"bytes,1,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Nombre               string   `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Cantidad             int32    `protobuf:"varint,3,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	Id                   int32    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_UploadBook) Reset()         { *m = Request_UploadBook{} }
func (m *Request_UploadBook) String() string { return proto.CompactTextString(m) }
func (*Request_UploadBook) ProtoMessage()    {}
func (*Request_UploadBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{0}
}

func (m *Request_UploadBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_UploadBook.Unmarshal(m, b)
}
func (m *Request_UploadBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_UploadBook.Marshal(b, m, deterministic)
}
func (m *Request_UploadBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_UploadBook.Merge(m, src)
}
func (m *Request_UploadBook) XXX_Size() int {
	return xxx_messageInfo_Request_UploadBook.Size(m)
}
func (m *Request_UploadBook) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_UploadBook.DiscardUnknown(m)
}

var xxx_messageInfo_Request_UploadBook proto.InternalMessageInfo

func (m *Request_UploadBook) GetChunks() []byte {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func (m *Request_UploadBook) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *Request_UploadBook) GetCantidad() int32 {
	if m != nil {
		return m.Cantidad
	}
	return 0
}

func (m *Request_UploadBook) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Response_UploadBook struct {
	State                int32    `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_UploadBook) Reset()         { *m = Response_UploadBook{} }
func (m *Response_UploadBook) String() string { return proto.CompactTextString(m) }
func (*Response_UploadBook) ProtoMessage()    {}
func (*Response_UploadBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{1}
}

func (m *Response_UploadBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_UploadBook.Unmarshal(m, b)
}
func (m *Response_UploadBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_UploadBook.Marshal(b, m, deterministic)
}
func (m *Response_UploadBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_UploadBook.Merge(m, src)
}
func (m *Response_UploadBook) XXX_Size() int {
	return xxx_messageInfo_Response_UploadBook.Size(m)
}
func (m *Response_UploadBook) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_UploadBook.DiscardUnknown(m)
}

var xxx_messageInfo_Response_UploadBook proto.InternalMessageInfo

func (m *Response_UploadBook) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type Request_DownloadBook struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_DownloadBook) Reset()         { *m = Request_DownloadBook{} }
func (m *Request_DownloadBook) String() string { return proto.CompactTextString(m) }
func (*Request_DownloadBook) ProtoMessage()    {}
func (*Request_DownloadBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{2}
}

func (m *Request_DownloadBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_DownloadBook.Unmarshal(m, b)
}
func (m *Request_DownloadBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_DownloadBook.Marshal(b, m, deterministic)
}
func (m *Request_DownloadBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_DownloadBook.Merge(m, src)
}
func (m *Request_DownloadBook) XXX_Size() int {
	return xxx_messageInfo_Request_DownloadBook.Size(m)
}
func (m *Request_DownloadBook) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_DownloadBook.DiscardUnknown(m)
}

var xxx_messageInfo_Request_DownloadBook proto.InternalMessageInfo

type Response_DownloadBook struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_DownloadBook) Reset()         { *m = Response_DownloadBook{} }
func (m *Response_DownloadBook) String() string { return proto.CompactTextString(m) }
func (*Response_DownloadBook) ProtoMessage()    {}
func (*Response_DownloadBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{3}
}

func (m *Response_DownloadBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_DownloadBook.Unmarshal(m, b)
}
func (m *Response_DownloadBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_DownloadBook.Marshal(b, m, deterministic)
}
func (m *Response_DownloadBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_DownloadBook.Merge(m, src)
}
func (m *Response_DownloadBook) XXX_Size() int {
	return xxx_messageInfo_Response_DownloadBook.Size(m)
}
func (m *Response_DownloadBook) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_DownloadBook.DiscardUnknown(m)
}

var xxx_messageInfo_Response_DownloadBook proto.InternalMessageInfo

type Request_Distribuir struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_Distribuir) Reset()         { *m = Request_Distribuir{} }
func (m *Request_Distribuir) String() string { return proto.CompactTextString(m) }
func (*Request_Distribuir) ProtoMessage()    {}
func (*Request_Distribuir) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{4}
}

func (m *Request_Distribuir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_Distribuir.Unmarshal(m, b)
}
func (m *Request_Distribuir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_Distribuir.Marshal(b, m, deterministic)
}
func (m *Request_Distribuir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_Distribuir.Merge(m, src)
}
func (m *Request_Distribuir) XXX_Size() int {
	return xxx_messageInfo_Request_Distribuir.Size(m)
}
func (m *Request_Distribuir) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_Distribuir.DiscardUnknown(m)
}

var xxx_messageInfo_Request_Distribuir proto.InternalMessageInfo

type Response_Distribuir struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Distribuir) Reset()         { *m = Response_Distribuir{} }
func (m *Response_Distribuir) String() string { return proto.CompactTextString(m) }
func (*Response_Distribuir) ProtoMessage()    {}
func (*Response_Distribuir) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{5}
}

func (m *Response_Distribuir) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Distribuir.Unmarshal(m, b)
}
func (m *Response_Distribuir) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Distribuir.Marshal(b, m, deterministic)
}
func (m *Response_Distribuir) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Distribuir.Merge(m, src)
}
func (m *Response_Distribuir) XXX_Size() int {
	return xxx_messageInfo_Response_Distribuir.Size(m)
}
func (m *Response_Distribuir) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Distribuir.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Distribuir proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Request_UploadBook)(nil), "comms.Request_UploadBook")
	proto.RegisterType((*Response_UploadBook)(nil), "comms.Response_UploadBook")
	proto.RegisterType((*Request_DownloadBook)(nil), "comms.Request_DownloadBook")
	proto.RegisterType((*Response_DownloadBook)(nil), "comms.Response_DownloadBook")
	proto.RegisterType((*Request_Distribuir)(nil), "comms.Request_Distribuir")
	proto.RegisterType((*Response_Distribuir)(nil), "comms.Response_Distribuir")
}

func init() {
	proto.RegisterFile("comms.proto", fileDescriptor_db39efb7717b7d47)
}

var fileDescriptor_db39efb7717b7d47 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x51, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x4c, 0x0a, 0xae, 0x60, 0xa9, 0x90, 0x58, 0xd2, 0x12, 0x02, 0x07, 0xe4, 0x13, 0x12, 0x52,
	0x0f, 0xf0, 0x07, 0x50, 0x4e, 0x70, 0xb2, 0xc4, 0xb9, 0xca, 0xc3, 0x12, 0x56, 0x89, 0x37, 0xc4,
	0x8e, 0xf8, 0x66, 0xfe, 0xa2, 0x69, 0x9a, 0x26, 0x6e, 0x72, 0xf3, 0xcc, 0x58, 0xbb, 0x33, 0xb3,
	0x70, 0x91, 0x52, 0x9e, 0x9b, 0x65, 0x51, 0x92, 0x25, 0x64, 0x0d, 0xe0, 0x05, 0xa0, 0x90, 0xbf,
	0x95, 0x34, 0x76, 0xfd, 0x55, 0xfc, 0x50, 0x9c, 0xbd, 0x12, 0x6d, 0x70, 0x01, 0xd3, 0xf4, 0xbb,
	0xd2, 0x1b, 0x13, 0xfa, 0x0f, 0xfe, 0xe3, 0x4c, 0xb4, 0x68, 0xc7, 0x6b, 0xca, 0x93, 0x52, 0x86,
	0x93, 0x9a, 0x3f, 0x17, 0x2d, 0xc2, 0x08, 0xce, 0xd2, 0x58, 0x5b, 0x95, 0xc5, 0x59, 0x78, 0x52,
	0x2b, 0x4c, 0x74, 0x18, 0x2f, 0x61, 0xa2, 0xb2, 0xf0, 0xb4, 0x61, 0xeb, 0x17, 0x7f, 0x82, 0x6b,
	0x21, 0x4d, 0x41, 0xda, 0x48, 0x77, 0x65, 0x00, 0xcc, 0xd8, 0xd8, 0xca, 0x66, 0x23, 0x13, 0x7b,
	0xc0, 0x17, 0x10, 0x1c, 0xec, 0xad, 0xe8, 0x4f, 0x1f, 0x7e, 0xf3, 0x1b, 0x98, 0x77, 0x43, 0x8e,
	0x84, 0xa0, 0xcf, 0xb3, 0x52, 0xc6, 0x96, 0x2a, 0xa9, 0x54, 0xc9, 0xe7, 0xce, 0xce, 0x9e, 0x7e,
	0xfe, 0xf7, 0x81, 0xbd, 0xed, 0x6a, 0xc0, 0x77, 0x00, 0xc7, 0xcb, 0xed, 0x72, 0xdf, 0xd4, 0xb8,
	0x99, 0x28, 0xea, 0xa4, 0x51, 0x04, 0xee, 0xe1, 0x07, 0xcc, 0x5c, 0x37, 0x78, 0x37, 0x18, 0xe4,
	0x8a, 0xd1, 0xfd, 0x70, 0xd4, 0x51, 0x10, 0x0f, 0x3f, 0xe1, 0xaa, 0xf7, 0xba, 0x6e, 0x2f, 0x30,
	0xb4, 0xd6, 0xff, 0x18, 0x5b, 0x73, 0x0a, 0xf0, 0x92, 0x69, 0x73, 0xf6, 0x97, 0x6d, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0xbb, 0xc5, 0x40, 0x05, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommsClient is the client API for Comms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommsClient interface {
	UploadBook(ctx context.Context, in *Request_UploadBook, opts ...grpc.CallOption) (*Response_UploadBook, error)
	DownloadBook(ctx context.Context, in *Request_DownloadBook, opts ...grpc.CallOption) (*Response_DownloadBook, error)
	DistribuirChunks(ctx context.Context, in *Request_Distribuir, opts ...grpc.CallOption) (*Response_Distribuir, error)
}

type commsClient struct {
	cc grpc.ClientConnInterface
}

func NewCommsClient(cc grpc.ClientConnInterface) CommsClient {
	return &commsClient{cc}
}

func (c *commsClient) UploadBook(ctx context.Context, in *Request_UploadBook, opts ...grpc.CallOption) (*Response_UploadBook, error) {
	out := new(Response_UploadBook)
	err := c.cc.Invoke(ctx, "/comms.Comms/UploadBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) DownloadBook(ctx context.Context, in *Request_DownloadBook, opts ...grpc.CallOption) (*Response_DownloadBook, error) {
	out := new(Response_DownloadBook)
	err := c.cc.Invoke(ctx, "/comms.Comms/DownloadBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commsClient) DistribuirChunks(ctx context.Context, in *Request_Distribuir, opts ...grpc.CallOption) (*Response_Distribuir, error) {
	out := new(Response_Distribuir)
	err := c.cc.Invoke(ctx, "/comms.Comms/Distribuir_chunks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommsServer is the server API for Comms service.
type CommsServer interface {
	UploadBook(context.Context, *Request_UploadBook) (*Response_UploadBook, error)
	DownloadBook(context.Context, *Request_DownloadBook) (*Response_DownloadBook, error)
	DistribuirChunks(context.Context, *Request_Distribuir) (*Response_Distribuir, error)
}

// UnimplementedCommsServer can be embedded to have forward compatible implementations.
type UnimplementedCommsServer struct {
}

func (*UnimplementedCommsServer) UploadBook(ctx context.Context, req *Request_UploadBook) (*Response_UploadBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBook not implemented")
}
func (*UnimplementedCommsServer) DownloadBook(ctx context.Context, req *Request_DownloadBook) (*Response_DownloadBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadBook not implemented")
}
func (*UnimplementedCommsServer) DistribuirChunks(ctx context.Context, req *Request_Distribuir) (*Response_Distribuir, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistribuirChunks not implemented")
}

func RegisterCommsServer(s *grpc.Server, srv CommsServer) {
	s.RegisterService(&_Comms_serviceDesc, srv)
}

func _Comms_UploadBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_UploadBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).UploadBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/UploadBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).UploadBook(ctx, req.(*Request_UploadBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_DownloadBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_DownloadBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).DownloadBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/DownloadBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).DownloadBook(ctx, req.(*Request_DownloadBook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comms_DistribuirChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request_Distribuir)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommsServer).DistribuirChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comms.Comms/DistribuirChunks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommsServer).DistribuirChunks(ctx, req.(*Request_Distribuir))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comms.Comms",
	HandlerType: (*CommsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadBook",
			Handler:    _Comms_UploadBook_Handler,
		},
		{
			MethodName: "DownloadBook",
			Handler:    _Comms_DownloadBook_Handler,
		},
		{
			MethodName: "Distribuir_chunks",
			Handler:    _Comms_DistribuirChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comms.proto",
}
